// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace ef_interactions.nplusone.CompiledModels
{
    public partial class AppDbContextModel
    {
        private AppDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("fe3b56fe-7aa0-423d-97d5-c4cdc8d0249c"), entityTypeCount: 5)
        {
        }

        partial void Initialize()
        {
            var customer = CustomerEntityType.Create(this);
            var order = OrderEntityType.Create(this);
            var orderItem = OrderItemEntityType.Create(this);
            var product = ProductEntityType.Create(this);
            var productCategory = ProductCategoryEntityType.Create(this);

            OrderEntityType.CreateForeignKey1(order, customer);
            OrderItemEntityType.CreateForeignKey1(orderItem, order);
            OrderItemEntityType.CreateForeignKey2(orderItem, product);
            ProductEntityType.CreateForeignKey1(product, productCategory);

            CustomerEntityType.CreateAnnotations(customer);
            OrderEntityType.CreateAnnotations(order);
            OrderItemEntityType.CreateAnnotations(orderItem);
            ProductEntityType.CreateAnnotations(product);
            ProductCategoryEntityType.CreateAnnotations(productCategory);

            AddAnnotation("ProductVersion", "10.0.8");
            AddAnnotation("Proxies:ChangeTracking", false);
            AddAnnotation("Proxies:CheckEquality", false);
            AddAnnotation("Proxies:LazyLoading", true);
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
