// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using ef_interactions.nplusone;
using ef_interactions.nplusone.CompiledModels;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(AppDbContext), typeof(AppDbContextModel))]
