    ALTER TABLE Orders
ADD 
    Status         NVARCHAR(50)   NOT NULL  DEFAULT 'Pending',
    TransactionId  NVARCHAR(100)  NULL;

ALTER DATABASE CompanyDb 
SET ALLOW_SNAPSHOT_ISOLATION ON;

ALTER DATABASE CompanyDb
SET READ_COMMITTED_SNAPSHOT ON;